apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  # Add this line
  resources:
    requests:
      storage: 10Gi
